### ISSUE TITLE
Palette Choice not updating

### ISSUE THREAD

**Issue by miketrethewey** [fatmanspanda/ALttPNG#1]
`palChoice` doesn't seem to be able to properly grab the current choice of the "combobox" (I have no idea what these things are called in Java) and doesn't allow for "Extract palette from last block of PNG" option which is like the whole reason this app exists.

**Comment by Zayik** [comment]
Duplicate palOptions combo box was in both the Class, and Main function. The GUI creation was done in scope of Main function, however, the function ConvertPngToSpr was not in scope of Main. Hence any changes made to the combo box affected the local copy from Main, but not the classes copy which was used.
